name: Documentation

on: pull_request

jobs:
    deploy:
        name: Deploy to Github pages
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            
            - name: Install Doxygen
              run: sudo apt-get install doxygen
              
            - name: Install Graphviz
              run: sudo apt-get install graphviz
              
            - name: Generate docs
              run: doxygen Doxyconf

            - name: Push git subdir branch
              uses: s0/git-publish-subdir-action@v2.4.0

              env:
                REPO: self
                BRANCH: documentation
                FOLDER: DOCS/html
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}